# Generated by Django 4.2.10 on 2024-03-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='comments',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='films',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
