# Generated by Django 4.2.10 on 2024-03-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCinema', '0002_films_comments_films_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='films',
            name='zhanre_title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
