# Generated by Django 4.2.10 on 2024-03-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCinema', '0003_films_zhanre_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='film_title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
