# Generated by Django 4.2.10 on 2024-03-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCinema', '0004_comment_film_title_comment_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_ava',
            field=models.CharField(default='', max_length=25251),
        ),
    ]
