# Generated by Django 4.2.10 on 2024-03-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCinema', '0005_comment_user_ava'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ava',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='saves_film',
            field=models.ManyToManyField(blank=True, to='appCinema.films'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_ava',
            field=models.CharField(default='default_user.jpg', max_length=25251),
        ),
    ]
