# Generated by Django 4.2.10 on 2024-03-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCinema', '0006_alter_account_ava_alter_account_saves_film_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_ava',
            field=models.CharField(default='media/default_user.png', max_length=25251),
        ),
    ]
